spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.sqlite.JDBC
      url: ${SQLITE_URL:jdbc:sqlite:file:./attachment/db/admin.sqlite}
      username:
      password:

      # Druid 连接池配置
      initial-size: 5              # 初始连接数
      min-idle: 5                  # 最小空闲连接数
      max-active: 20               # 最大活跃连接数
      max-wait: 60000              # 获取连接的最大等待时间（毫秒）

      # Druid 数据源监控
      filters: stat, wall    # 过滤器，可以选择不同的监控功能
      max-open-prepared-statements: 20 # 最大打开的 PreparedStatement 数量
      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1 # 允许访问的 IP，多个 IP 用逗号分隔
        deny:
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除的 URL

      # 配置监控相关
      use-global-data-source-stat: true  # 是否开启全局数据源统计
      validation-query: SELECT 1         # 连接验证查询
      test-on-borrow: true               # 取连接时进行检查
      test-while-idle: true              # 空闲时检查连接
      test-on-return: false              # 还连接时进行检查

# 配置 Druid 的监控页面
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    druid:
      enabled: true